name: 'Patrol Board'
description: 'A GitHub Action that periodically runs scripts and displays/updates the results as a dashboard in GitHub Issues'
inputs:
  script:
    description: 'Path to the script to execute (`.ts` / `.js` / `.sh`)'
    required: true
  issue-title:
    description: 'Title of the Issue'
    required: true
  issue-label:
    description: 'Label to attach to the Issue'
    required: false
    default: ''
runs:
  using: 'node24'
  main: 'dist/index.js'
